name: Variables
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    env:
      USERNAME: ${{ secrets.USERNAME }}
    steps:
      - run: echo "${USERNAME}"
      - run: echo "${USERNAME:0:1} ${USERNAME#?}"
